#docker-compose.yaml

version: "3"
services:
  fastapi1:
    build: .
    container_name: fastapi1

  fastapi2:
    build: .
    container_name: fastapi2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports: # 내부 통신만 필요한 경우 외부 포트를 노출할 필요가 없으므로 생략 가능
      - "80:80" # 호스트의 80번 포트를 컨테이너의 80번 포트에 매핑
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # 호스트의 nginx/default.conf 파일을 컨테이너의 /etc/nginx/conf.d/default.conf에 마운트
    depends_on:
      - fastapi1
      - fastapi2
